### ISSUE TITLE
Can't read Parameters

### ISSUE THREAD

**Issue by ChristophCNC** [robert-budde/iHSV-Servo-Tool#11]
Hello,
Im facing the problem that I can't read the parameter for Servo V552
It all works fine just when I try to read the parameters the python software stop working and I get this error.

Traceback (most recent call last):
  File "ihsv-servo-tool.py", line 344, in readParams
    par_list = self.ihsv.get_parameter_list([self.cbSelectParameterGroup.currentText()])
  File "C:\users\mrpep\desktop\tool2\iHSV_Properties.py", line 9434, in get_parameter_list
    par_dict[par] = int(pars[par], 16)
TypeError: int() can't convert non-string with explicit base

**Comment by dominikdh** [comment]
Hello Christoph,

I think I found the bug (see my last commit). Unfortunately I am not able to test the software, because I do not own a v5 motor...

If it is still not working, please write again ;-)

**Comment by ChristophCNC** [comment]
so I just download the whole package agian?

**Comment by ChristophCNC** [comment]
I just downloaded just the package again, same issue. 
I'm also happy if you can send me the previous version.

Das nächste Bier geht auf mich sobald ich wieder in Düsseldorf bin ;)

'method' object is not connected
Traceback (most recent call last):
  File "ihsv-servo-tool.py", line 344, in readParams
    par_list = self.ihsv.get_parameter_list([self.cbSelectParameterGroup.currentText()])
  File "C:\users\mrpep\desktop\master\tool\iHSV_Properties.py", line 9434, in get_parameter_list
    par_dict[par] = int(pars[par], 16)
TypeError: int() can't convert non-string with explicit base

**Comment by dominikdh** [comment]
Are you sure, that you used my fixed version? 
I am new at using GitHub as a contributer, but I think my pull request is until now not merged by Robert into his master branch. If you clone so long my fork (https://github.com/dominikdh/iHSV-Servo-Tool/tree/v6_support) the fix should be included. 

It would be a pity if the current version is not working and the software cannot be used by new users, so  I am looking forward for feedback of v5 owners.

**Comment by ChristophCNC** [comment]
Hey, I tested the software and it's still not working. I go the old software today and the  old version is working fine, so there is no other problem. 
Yes, yesterday I was downloading the same sorftware again. It was already late, sorry.

Here the python error message,
(base) PS C:\users\mrpep\desktop\servo\iHSV-Servo-Tool-6_support> python iHSV-Servo-Tool.py
'method' object is not connected
Traceback (most recent call last):
  File "iHSV-Servo-Tool.py", line 367, in readParams
    item = QTableWidgetItem(str(configDataInfo[par]))
KeyError: 'Name'
(base) PS C:\users\mrpep\desktop\servo\iHSV-Servo-Tool-6_support>

Just send me the new version I will test it for you. 
Thank you!

**Comment by dominikdh** [comment]
Hey, I just updated my fork.
It is very unfavorable to write code without the possibility to test it... So sorry, if it is still not the last bug.
I will send a pull request if the software is working.

**Comment by ChristophCNC** [comment]
Hey Dominik, I just tested the software and I can say that it works fine!!!
I can read and change parameter and plot all signals!!

good job, thank you!!

**Comment by dominikdh** [comment]
I am glad to read that it is finally working :)
